tracer:
  property: "I AM THE DEV"

logging:
  file: "/Users/radustefanescu/IdeaProjects/microservicescomplete/application.log"

################### MongoDB Configuration ##########################
spring:
  data:
    mongodb:
      uri: "{cipher}da9c806a4f2bce825ff8e1fd721284209173ec9f1de72d1b8e24bd9c6de9789bf7626b9ae48ba1a7d5a395837c180bcb"
  cloud:
    stream:
      bindings:
        output:
          destination: orgChangeTopic
          content-type: application/json
        kafka:
          binder:
            zkNodes: localhost
            brokers: localhost
  zipkin:
    baseUrl: http://localhost:9411
management:
  endpoints:
    web:
      exposure:
        include: info, health, env
server:
  port: 8990
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: "{cipher}52ac05eaf78010a930625e730025cced00b6f16c4ec3fc19c7c513146d0007f03d8ee2f103aea595494a5944169ffef4"
  instance:
    preferIpAddress: true
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8071/user
